// <auto-generated />
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Data.Migrations
{
    [DbContext(typeof(CompraContext))]
    [Migration("20220615191926_CorrecionInicial")]
    partial class CorrecionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("BlazorApp1.Data.Models.Bebida", b =>
                {
                    b.Property<int>("BebidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BebidaId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Bebidas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("CarritoId");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Empanada", b =>
                {
                    b.Property<int>("EmpanadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmpanadaId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Empanadas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PizzaId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Torta", b =>
                {
                    b.Property<int>("TortaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_variedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TortaId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Tortas");
                });

            modelBuilder.Entity("BlazorApp1.Models.Choripan", b =>
                {
                    b.Property<int>("ChoripanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chimichurri")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Criolla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChoripanId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Choripanes");
                });

            modelBuilder.Entity("BlazorApp1.Models.HamburguesaCant", b =>
                {
                    b.Property<int>("HamburguesaCantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bacon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cebolla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cheddar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Huevo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jamon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ketchup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lechuga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayonesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mostaza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sabora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tomate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tybo")
                        .HasColumnType("INTEGER");

                    b.HasKey("HamburguesaCantId");

                    b.HasIndex("CarritoId");

                    b.ToTable("hamburguesaCantidades");
                });

            modelBuilder.Entity("BlazorApp1.Models.HamburguesaPrecio", b =>
                {
                    b.Property<int>("HamburguesaPrecioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bacon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cebolla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cheddar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Huevo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jamon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ketchup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lechuga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayonesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mostaza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sabora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tomate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tybo")
                        .HasColumnType("INTEGER");

                    b.HasKey("HamburguesaPrecioId");

                    b.HasIndex("CarritoId");

                    b.ToTable("HamburguesaPrecios");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Bebida", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("BebidasC")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Empanada", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("EmpanadasC")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Pizza", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("Pizzas")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Torta", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("Tortas")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Models.Choripan", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("ChoripanesC")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Models.HamburguesaCant", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany("Hamburguesas")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Models.HamburguesaPrecio", b =>
                {
                    b.HasOne("BlazorApp1.Data.Models.Carrito", "Carrito")
                        .WithMany()
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("BlazorApp1.Data.Models.Carrito", b =>
                {
                    b.Navigation("BebidasC");

                    b.Navigation("ChoripanesC");

                    b.Navigation("EmpanadasC");

                    b.Navigation("Hamburguesas");

                    b.Navigation("Pizzas");

                    b.Navigation("Tortas");
                });
#pragma warning restore 612, 618
        }
    }
}
